In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

# Extracting Data from database

In [2]:
#For clint details
print("Done start")
jobma_catcher_df = pd.read_sql("SELECT * FROM jobma_catcher", engine) #Client details 

jobma_login_df = pd.read_sql("SELECT * FROM jobma_login", engine) #Usage details
jobma_wallet_df = pd.read_sql("SELECT * FROM wallet", engine) #How aggresively using + how much #account Wallet info
jobma_subscription_df = pd.read_sql("SELECT * FROM subscription_history", engine) #how much frequently using #subscription history
print("1")


jobma_catcher_language_df = pd.read_sql("SELECT * FROM jobma_catcher_language", engine) #Account setttings 
default_assessment_kits_df = pd.read_sql("SELECT * FROM default_assessment_kits", engine) #Question types and kit and kits type created by client
job_assessment_kit_df = pd.read_sql("SELECT * FROM job_assessment_kit", engine) #kit created by client for interview #prerecorded
ai_video_kit_df = pd.read_sql("SELECT * FROM ai_video_kit", engine) #Kits created by client for AI interview      #Features using setttings (How much)
print("2")


jobma_pitcher_applied_jobs_df = pd.read_sql("SELECT * FROM jobma_pitcher_applied_jobs", engine) #How many jobs he is posting #Pitcher/Candidate details and status.
jobma_pitcher_df = pd.read_sql("SELECT * FROM jobma_pitcher", engine) #How many candidate #Pitcher/Candidate profile details.
print("3")

jobma_employer_job_posting_df = pd.read_sql("SELECT * FROM jobma_employer_job_posting", engine) #how many positions he has created
jobma_pitcher_invitations_df = pd.read_sql("SELECT * FROM jobma_pitcher_invitations", engine) #Interview 
print("4")

jobma_interviews_df = pd.read_sql("SELECT * FROM jobma_interviews", engine) #candidate interview response data (just for pre-recorded type)
jobma_interviews_online_df = pd.read_sql("SELECT * FROM jobma_interviews_online", engine) ##candidate interview response data (just for live interview type)
jobma_ai_interviews_df = pd.read_sql("SELECT * FROM jobma_ai_interviews", engine) #candidate interview response data
print("5")


report_df = pd.read_sql("SELECT * FROM report", engine) #different types of saved reports.
shared_report_df = pd.read_sql("SELECT * FROM shared_report", engine) #subscription history #Share with sub-account or with main account.
print("Final Done")

Done start
1
2
3
4
5
Final Done

In [3]:
jobma_pitcher_applied_jobs_df

,jobma_applied_id,jobma_pitcher_id,jobma_post_id,catcher_id,jobma_applied_date,jobma_contacted_date,jobma_contacted_text,status,tags,jobma_assessment_id,...,avg_ai_score,stages_status,pre_screen_qualify,integration_source,source,export,deleted_rounds,deleted_at,created_at,updated_at
0,154,77463,34345,0.0,2012-06-29 00:00:00,0000-00-00,,0,,0.0,...,NaN,1,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2024-05-16 17:47:20
1,155,1,145,92.0,2012-07-19 00:00:00,0000-00-00,,3,,0.0,...,NaN,0,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2021-07-07 11:48:54
2,156,355,145,92.0,2012-07-19 00:00:00,0000-00-00,slected,2,"arp,",0.0,...,NaN,0,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2021-07-07 11:48:54
3,157,354,145,92.0,2012-07-19 00:00:00,0000-00-00,,3,"arp,",0.0,...,NaN,0,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2021-07-07 11:48:54
4,158,356,145,92.0,2012-07-19 00:00:00,0000-00-00,,3,,0.0,...,NaN,0,None,None,Jobma,0,None,NaT,2018-01-24 12:36:09,2021-07-07 11:48:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54956,65693,1127179,0,8893.0,2025-03-28 07:01:41,2025-03-28,,0,,NaN,...,NaN,1,None,None,None,0,None,NaT,2025-03-28 07:01:41,2025-03-28 12:31:41
54957,65695,1126639,33979,1873.0,2025-04-01 06:23:45,2025-04-01,,0,,NaN,...,NaN,0,None,None,None,0,None,NaT,2025-04-01 06:23:45,2025-04-01 06:23:45
54958,65697,1127207,0,8464.0,2025-04-02 09:17:50,2025-04-02,,0,,NaN,...,NaN,1,0,None,None,0,None,NaT,2025-04-02 09:17:50,2025-04-02 14:47:50
54959,65699,1127213,35855,8464.0,2025-04-02 10:08:28,2025-04-02,,0,,NaN,...,NaN,1,0,None,None,0,None,NaT,2025-04-02 10:08:28,2025-04-02 15:38:28
54960,65701,1127227,33979,1873.0,2025-04-03 10:28:15,2025-04-03,,0,,NaN,...,NaN,0,None,None,None,0,None,NaT,2025-04-03 10:28:15,2025-04-03 10:28:15

In [4]:
#Function
def compute_value_counts(df):
    for column in df.columns:
        print(f"No. unique value for {column}:---{df[column].nunique()}")
        print(df[column].value_counts(dropna=False).head(10))
        print("--" * 20, "\n")

# Working on jobma_catcher

In [5]:
jobma_catcher_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7672 entries, 0 to 7671
Data columns (total 75 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   jobma_catcher_id                7672 non-null   int64
 1   jobma_catcher_fname             7672 non-null   object
 2   jobma_catcher_lname             7672 non-null   object
 3   jobma_catcher_dob               1071 non-null   object
 4   jobma_catcher_video_status      2018 non-null   object
 5   jobma_catcher_company           7672 non-null   object
 6   org_type                        7672 non-null   object
 7   sec_ques_id                     7672 non-null   int64
 8   security_ans                    7672 non-null   object
 9   jobma_about_company             7672 non-null   object
 10  jobma_functional                7672 non-null   object
 11  jobma_catcher_indus             6126 non-null   object
 12  jobma_company_email             7672 non-null   object
 13  jobma_catcher_email             7672 non-null   object
 14  jobma_catcher_title             7672 non-null   int64
 15  jobma_catcher_ext               7672 non-null   object
 16  jobma_catcher_otype             7672 non-null   object
 17  jobma_catcher_photo             7672 non-null   object
 18  jobma_catcher_logo              104 non-null    object
 19  jobma_catcher_website           7672 non-null   object
 20  jobma_company_address           7672 non-null   object
 21  jobma_catcher_address2          972 non-null    object
 22  jobma_catcher_video             7672 non-null   object
 23  jobma_catcher_city              7672 non-null   int64
 24  jobma_catcher_state             7672 non-null   int64
 25  jobma_catcher_country           7672 non-null   int64
 26  jobma_catcher_zip               7672 non-null   object
 27  jobma_catcher_fax               6308 non-null   object
 28  jobma_catcher_phone             7672 non-null   object
 29  jobma_catcher_status            7649 non-null   object
 30  jobma_catcher_creation          7672 non-null   object
 31  jobma_catcher_type              5425 non-null   object
 32  jobma_catcher_sub_accounts      7672 non-null   object
 33  is_premium                      7672 non-null   object
 34  jobma_catcher_parent            7672 non-null   int64
 35  jobma_catcher_is_deleted        257 non-null    object
 36  jobma_verified                  7672 non-null   object
 37  jobma_in_index                  7354 non-null   object
 38  data_access                     7672 non-null   object
 39  subscription_status             7672 non-null   object
 40  interview_rate                  7672 non-null   float64
 41  remember_token                  7672 non-null   object
 42  deleted_at                      459 non-null    datetime64[ns]
 43  api_key                         7672 non-null   object
 44  sub_user                        7672 non-null   int64
 45  per_sub_user                    7672 non-null   object
 46  live_interview_credit           7672 non-null   float64
 47  pre_recorded_credit             7672 non-null   float64
 48  ai_live_interview_credit        7672 non-null   float64
 49  credit_value                    7672 non-null   int64
 50  interview_cost_type             7672 non-null   object
 51  subscription_type               7672 non-null   object
 52  phone_call_cost_type            7672 non-null   object
 53  call_and_regording_credits      82 non-null     float64
 54  transcription_credits           82 non-null     float64
 55  temp_subscription_type          7672 non-null   object
 56  created_at                      7672 non-null   datetime64[ns]
 57  updated_at                      7672 non-null   datetime64[ns]
 58  jobma_support_rtc               7672 non-null   object
 59  interview_question              7672 non-null   int64
 60  video_recording_suppport        7672 non-null   object
 61  subaccount_permission           7670 non-null   object
 62  reply_email                     1 non-null      object
 63  sing_up_canditate_after_apply   7672 non-null   object
 64  currency                        7672 non-null   object
 65  referral_credit                 7672 non-null   int64
 66  company_size                    5934 non-null   object
 67  theme                           7672 non-null   object
 68  flag                            7672 non-null   object
 69  jobma_auto_recording_status     7672 non-null   object
 70  jobma_scenario_question_status  7672 non-null   object
 71  ai_live_interview               7672 non-null   object
 72  ms_teams_chat_reference         1 non-null      object
 73  bot_audio                       7672 non-null   int64
 74  approval                        7672 non-null   object
dtypes: datetime64[ns](3), float64(6), int64(12), object(54)
memory usage: 4.4+ MB

In [6]:
# jobma_catcher_df.columns

In [7]:
selected_columns = ['jobma_catcher_id',
                    'jobma_functional',
                    'jobma_catcher_indus',
                    'jobma_catcher_status',
                    'jobma_catcher_creation',
                    'jobma_catcher_type',
                    'jobma_catcher_sub_accounts',
                    'is_premium','jobma_catcher_parent',
                    'jobma_catcher_is_deleted',
                    'jobma_verified',
                    'subscription_status',
                    'interview_rate',
                    'deleted_at',
                    'sub_user',
                    'per_sub_user',
                    'subscription_type',
                    'created_at',
                    'updated_at',
                    'company_size']
catcher_selected_df = jobma_catcher_df[selected_columns].copy()

In [8]:
# catcher_selected_df

# Now Jobma_login_df

In [9]:
jobma_login_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39321 entries, 0 to 39320
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   jobma_login_id       39321 non-null  int64
 1   jobma_user_name      39321 non-null  object
 2   jobma_password       39321 non-null  object
 3   jobma_role_id        39321 non-null  int64
 4   jobma_user_id        39321 non-null  int64
 5   jobma_last_login     37785 non-null  object
 6   jobma_created_by     7854 non-null   object
 7   confirmed            39321 non-null  int64
 8   confirmation_code    39321 non-null  object
 9   jobma_login_status   7924 non-null   object
 10  jobma_login_ip       39321 non-null  object
 11  forget_password      245 non-null    object
 12  remember_token       39321 non-null  object
 13  jobma_social_login   39321 non-null  int64
 14  password_changed_at  39321 non-null  datetime64[ns]
 15  deleted_at           84 non-null     datetime64[ns]
 16  created_at           39321 non-null  object
 17  updated_at           39321 non-null  object
 18  google2fa_secret     0 non-null      object
 19  two_factor_status    39321 non-null  object
 20  two_factor_type      39321 non-null  object
dtypes: datetime64[ns](2), int64(5), object(14)
memory usage: 6.3+ MB

In [10]:
jobma_login_df

,jobma_login_id,jobma_user_name,jobma_password,jobma_role_id,jobma_user_id,jobma_last_login,jobma_created_by,confirmed,confirmation_code,jobma_login_status,...,forget_password,remember_token,jobma_social_login,password_changed_at,deleted_at,created_at,updated_at,google2fa_secret,two_factor_status,two_factor_type
0,1,existinguser@example.com,hashedpassword,4,1001,None,None,1,1,0,...,1,,0,2020-10-30 03:57:14,NaT,2024-09-26 16:21:36,2024-09-26 16:21:36,None,0,0
1,240,superadmin@mailinator.com,$2y$10$TyEFO2DlIqVuwnpn1yDRUeRjIklsTP6Rkiq09sn...,1,162,2024-10-18 07:38:58,0,1,,1,...,None,N52TQOQ1aR3iA8VVC269FnEFApjJM3M1QqW0BOquGr6cIH...,0,2020-05-15 11:50:25,NaT,0000-00-00 00:00:00,2024-10-18 07:38:58,None,0,0
2,535,gaurava@selectsourceintl.com,$2y$10$WEnjfOt4vTnq/x50aYNaE.zDrr4F00EB37NnnYC...,5,96,0000-00-00 00:00:00,0,0,,1,...,0,UBzEkXCpiagAdQiZvHDSMxbu0lQZy3cicuRIf5pFXZWknT...,0,2020-05-15 11:50:25,NaT,2016-11-23 20:53:27,2017-05-09 18:06:45,None,0,0
3,642,SMandeep@selectsourceintl.com,$2y$10$Lj1NrtAvq0KSPu4VM4/sAOUaq1UCHYf0zo1xbcF...,5,557,0000-00-00 00:00:00,1,0,,1,...,1,K5qiDGmZ4UhgBtz94isKfNXo3R01Pi4EJx9AwwyXIrBWjE...,0,2020-05-15 11:50:25,NaT,0000-00-00 00:00:00,2018-02-09 01:02:45,None,0,0
4,993,ywangb13@gmail.com,2982087bec56338d021c81e0bac623a0,4,908,0000-00-00 00:00:00,1,1,,1,...,None,,0,2020-05-15 11:50:25,NaT,0000-00-00 00:00:00,0000-00-00 00:00:00,None,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39316,112385,pratikabc9@yopmail.com,$2b$10$VmMPRrRKW61t4mTIWcovr.dguenWGVUEGmYGUOE...,4,1127089,None,None,1,1,0,...,None,,0,2025-03-26 16:55:35,NaT,2025-03-26 11:25:35,2025-03-26 11:25:35,None,0,0
39317,112387,pratikabc10@yopmail.com,$2b$10$6A5AUWsFx86xHxgYH.eFG.FdyuzcdQrmatTv8IP...,4,1127091,None,None,1,1,0,...,None,,0,2025-03-26 16:56:55,NaT,2025-03-26 11:26:56,2025-03-26 11:26:56,None,0,0
39318,112389,ramesh23@yopmail.com,$2b$10$pBYHn72SXg4RULY5rV1L0uhRQOmcueI.g3OZDbm...,4,1127093,2025-03-26 12:57:28,None,1,1,0,...,None,,0,2025-03-26 17:26:35,NaT,2025-03-26 11:56:36,2025-03-26 11:56:36,None,0,0
39319,112391,ramesh21@yopmail.com,$2b$10$tG9Uy9StD4OOPfR7ZeTyR.TLgmrjZSxP5zqWPFp...,4,1127095,None,None,1,1,0,...,None,,0,2025-03-26 18:28:10,NaT,2025-03-26 12:58:10,2025-03-26 12:58:10,None,0,0
39320,112393,Sergebrian@yopmail.com,$2y$10$p9mNtOk4sjZJU7EMIMiqjeesQf5jvUzvVSYgDNQ...,3,9445,0000-00-00 00:00:00,1,1,,0,...,None,,0,2025-03-28 10:45:12,NaT,2025-03-28 05:15:12,2025-03-28 05:15:12,None,0,0

In [11]:
login_selected_df = jobma_login_df[['jobma_login_id', #id
                                    'jobma_role_id', #id
                                    'jobma_user_id', #id
                                    'jobma_last_login', #last use
                                    'jobma_created_by', 
                                    'confirmed', #0,1
                                    'deleted_at', 
                                    'created_at', 
                                    'updated_at']].copy()

In [12]:
login_selected_df

,jobma_login_id,jobma_role_id,jobma_user_id,jobma_last_login,jobma_created_by,confirmed,deleted_at,created_at,updated_at
0,1,4,1001,None,None,1,NaT,2024-09-26 16:21:36,2024-09-26 16:21:36
1,240,1,162,2024-10-18 07:38:58,0,1,NaT,0000-00-00 00:00:00,2024-10-18 07:38:58
2,535,5,96,0000-00-00 00:00:00,0,0,NaT,2016-11-23 20:53:27,2017-05-09 18:06:45
3,642,5,557,0000-00-00 00:00:00,1,0,NaT,0000-00-00 00:00:00,2018-02-09 01:02:45
4,993,4,908,0000-00-00 00:00:00,1,1,NaT,0000-00-00 00:00:00,0000-00-00 00:00:00
...,...,...,...,...,...,...,...,...,...
39316,112385,4,1127089,None,None,1,NaT,2025-03-26 11:25:35,2025-03-26 11:25:35
39317,112387,4,1127091,None,None,1,NaT,2025-03-26 11:26:56,2025-03-26 11:26:56
39318,112389,4,1127093,2025-03-26 12:57:28,None,1,NaT,2025-03-26 11:56:36,2025-03-26 11:56:36
39319,112391,4,1127095,None,None,1,NaT,2025-03-26 12:58:10,2025-03-26 12:58:10
39320,112393,3,9445,0000-00-00 00:00:00,1,1,NaT,2025-03-28 05:15:12,2025-03-28 05:15:12

In [13]:
login_selected_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39321 entries, 0 to 39320
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   jobma_login_id    39321 non-null  int64
 1   jobma_role_id     39321 non-null  int64
 2   jobma_user_id     39321 non-null  int64
 3   jobma_last_login  37785 non-null  object
 4   jobma_created_by  7854 non-null   object
 5   confirmed         39321 non-null  int64
 6   deleted_at        84 non-null     datetime64[ns]
 7   created_at        39321 non-null  object
 8   updated_at        39321 non-null  object
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 2.7+ MB

# Now jobma_wallet_df

In [14]:
jobma_wallet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5562 entries, 0 to 5561
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    5562 non-null   int64
 1   catcher_id            5562 non-null   int64
 2   credit_amount         165 non-null    float64
 3   wallet_amount         5562 non-null   float64
 4   subscription_type     5562 non-null   object
 5   plan_type             5562 non-null   object
 6   is_unlimited          5562 non-null   object
 7   premium_storage       5562 non-null   int64
 8   trial_account_type    5161 non-null   float64
 9   gst_code              2781 non-null   object
 10  billing_cycle         2 non-null      object
 11  billing_cycle_status  5562 non-null   object
 12  created_at            5562 non-null   datetime64[ns]
 13  updated_at            5562 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 608.5+ KB

In [15]:
jobma_wallet_df

,id,catcher_id,credit_amount,wallet_amount,subscription_type,plan_type,is_unlimited,premium_storage,trial_account_type,gst_code,billing_cycle,billing_cycle_status,created_at,updated_at
0,1,669,NaN,0.0,0,0,0,0,NaN,None,None,0,2017-11-03 12:10:27,2017-11-03 12:10:27
1,2,92,NaN,34.0,0,0,0,0,0.0,None,None,0,2017-11-03 12:10:27,2020-02-20 07:10:00
2,3,898,NaN,0.0,0,0,0,0,NaN,None,None,0,2017-11-03 04:36:27,2017-11-03 04:36:27
3,4,912,NaN,0.0,0,0,0,0,NaN,None,None,0,2017-11-03 14:08:57,2017-11-03 14:08:57
4,5,92,NaN,3.0,0,0,0,0,0.0,None,None,0,2017-11-03 14:08:57,2020-02-20 07:10:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5557,5985,9319,NaN,500000.0,0,0,1,0,0.0,None,None,1,2024-06-12 11:14:07,2024-07-02 12:56:06
5558,5987,9365,NaN,137.0,0,0,0,0,0.0,,None,0,2024-07-11 08:05:25,2024-07-17 09:32:21
5559,5989,9405,NaN,500000.0,0,0,1,0,0.0,None,None,0,2024-09-04 05:01:02,2024-09-04 05:01:02
5560,5991,9413,NaN,15000.0,0,0,0,0,0.0,,None,0,2024-09-24 09:18:45,2024-09-24 09:20:17
5561,5993,9445,NaN,150.0,0,0,0,0,0.0,None,None,0,2025-03-28 05:15:12,2025-03-28 05:15:12

In [16]:
jobma_wallet_df.columns

Index(['id', 'catcher_id', 'credit_amount', 'wallet_amount',
       'subscription_type', 'plan_type', 'is_unlimited', 'premium_storage',
       'trial_account_type', 'gst_code', 'billing_cycle',
       'billing_cycle_status', 'created_at', 'updated_at'],
      dtype='object')

In [17]:
jobma_wallet_selected_df = jobma_wallet_df[['id', 
                                            'catcher_id',
                                            'credit_amount',#
                                            'wallet_amount', #amounts or balance may be 
                                            'subscription_type', #0,1
                                            'plan_type',#0,1
                                            'is_unlimited',#0, 1
                                            'billing_cycle_status',#0,1 may be koi relation ho plan se ya user type se
                                            'created_at',# there may be many created and updated column
                                            'updated_at'
                                         ]].copy()

In [18]:
wallet_selected_df

NameError: name 'wallet_selected_df' is not defined

In [ ]:
wallet_selected_df.info()

# Jobma Subscription_df

In [ ]:
jobma_subscription_df #Active users and non active uesrs

In [ ]:
# jobma_subscription_df['recurring_data'].value_counts()

In [ ]:
jobma_subscription_df['recurring_data'].nunique()

In [ ]:
"""
catcher_id,#Many times in table
'catcher_email', #no use
'sub_user_id' #
"""

In [ ]:
subscription_selected_df = jobma_subscription_df[['id', #starts from 2
                                                  'catcher_id', #duplicated catcher id as has buy many times
                                                  'sub_user_id', #sub users and admins too many with same id
                                                  'subscription_id',#1,2
                                                  'premium_plan_id',#1.0,2.0,3.0,....10.0
                                                  'premium_plan', #category of different different plans
                                                  'subscription_amount',#plan prices------------>May be................??
                                                  'credit_given', #How much credits they got on buying
                                                  'expiry_date',
                                                  'currency', #0,1
                                                  'currency_val',#different values given
                                                  'recurring_data', #Categorial data #Text data
                                                  'status',# iska nahi pta hai
                                                  'payment_status', #
                                                  'created_at',
                                                  'updated_at'
                                                 ]].copy()

In [ ]:
subscription_selected_df

In [ ]:
subscription_selected_df.info()

In [ ]:
subscription_selected_df.isnull().sum()

# How much features and and how many features used by client

# jobma_catcher_language_df

In [ ]:
# jobma_catcher_language_df

In [ ]:
jobma_catcher_language_df.info()

In [ ]:
jobma_catcher_language_df

In [ ]:
#These are the features And seting which the clients are using
jobma_catcher_language_selected_df=jobma_catcher_language_df[['id',
                                                              'catcher_id',
                                                              #'lang_value', #eng,per,etc, not much useful
                                                              # 'emp_date_format', #Date formate
                                                              'interview_reminder', #intervieww reminder times how many times he invited
                                                              #'interview_privacy_text',
                                                              #'interview_instruction',
                                                              #'practice_question_enable',  # enable right now 
                                                              #'practice_question',   #Has 37 unique questionset or questions
                                                              #'background_image',#mostly null
                                                              #'addons_transcription', #0,1 --->0
                                                              'ats_email_notification',#1,0
                                                              # 'ats_email_id',
                                                              # 'prerecorded_email_id',
                                                              # 'prerecorded_email_notification',
                                                              # 'live_schedule_notification',
                                                              # 'ai_live_email_notification',#0,1-->0
                                                              # 'ai_live_email_id', #mostly null has emailss
                                                              # 'invite_guests', #0,1-->0
                                                              # 'invite_hosts', #0,1-->0
                                                              # 'two_factor_authentication', #0,1
                                                              # 'ai_scoring', #0,1-->0
                                                              # 'interview_setting', #blur, flase basically all are bg for interview
                                                              'interview_configuration', #redflags, timezone, liveEmail, liveEmail #may be use full for candidates eval or proctoring
                                                              # 'redirect_url', #when does interview or ..done
                                                              # 'timezone', #0,1-->0
                                                              # 'live_interview_source	', #0,1-->0
                                                              # 'auto_recording', #0-->0
                                                              # 'scenario_question', #0,1-->0
                                                              # 'share_evaluation_pre_post', #0,1-->0
                                                              # 'custom_background', #most null about image in bg
                                                              # 'theme', #0,1-->0
                                                              # 'interview_expiry_days', #many valuesss
                                                              # 'sms_messages', #Categorial data   #"live": null, "on_hold": "Your application for [POSITION] is put (On hold) by
                                                                                                      #the employer.Check your Jobma for details. We wish you luck 
                                                              # 'prerecorded_sms', #mostly null #ategory
                                                              # 'live_sms', #mostly null #ategory
                                                              # 'share_evaluation', #7,51,60 #mostly 7
                                                              # 'ai_video_accent',
                                                              # 'created_at',
                                                              # 'updated_at'
                                                             ]].copy()

In [ ]:
jobma_catcher_language_df['ai_video_accent'].value_counts()

In [ ]:
jobma_catcher_language_df.iloc[:, 30:50].head(4)

# default_assessment_kits-------------------------

In [ ]:
default_assessment_kits_df

In [ ]:
#These are the features And seting which the clients are using
default_assessment_kits_selected_df=default_assessment_kits_df[['id',
                                                                'kit_name',#may be question set  from data science, testing, sw et
                                                                'interview_type', #0
                                                                'interview_category', #category of interview ,1,2,3,4,5,-->0
                                                                'category_id', #lot of category id 15,17,56,57,77,177
                                                                'sub_category_id',  #float values 1.0,2.0,4.0,12.0......
                                                                'kit_description', #Description about questions
                                                                'ques_ids', #ids of questions
                                                                'industry_id', #industry id 1,23,28,14,... from which type of industry belong these questions
                                                                'status', #1
                                                                'created_at',
                                                                'updated_at'
                                                               ]].copy()

In [ ]:
default_assessment_kits_df.iloc[:, 30:50].head(4)

In [ ]:
default_assessment_kits_df['interview_type'].unique()

# job_assessment_kit
#Hold the information about how the interview gone and evaluation
# Kits created by employers for Pre-recorded interview :  Tells How frequently he is using for interview

In [ ]:
job_assessment_kit_df

In [ ]:
job_assessment_kit_df['is_streaming'].value_counts().head(10)

In [ ]:
#These are the features And seting which the clients are using
job_assessment_kit_selected_df=job_assessment_kit_df[['id',
                                                      'catcher_id',
                                                      'title', #May be it may be title, intervie, test, system analyst, automation,
                                                      'slug', #slug, bash, test, people, react, testkit, checked, test-essay
                                                      'answer_duration', #how much time did student takes to finish the test
                                                      'interview_type',  #1, 2, 3, 4, Type of interview given live, ailive, video
                                                      'question_set', #Description about questions
                                                      'ques_ids', #Set of questions given to candidate #Can tell which type of candidate like tech non tech, finance etc
                                                      'pre_screening', #question given to candidates for prescreanings
                                                      'ques_ids', #
                                                      'weightage', #0,1-->0
                                                      'weightage_data', #mostly null
                                                      'description', #Dscription
                                                      'price', #0,100,10,3,1
                                                      'currency', #usd
                                                      'expiry', #expiration date mostly null
                                                      'status', #1,0-->1
                                                      'is_active', #1,0-->1
                                                      'offer_status', #active, inactive----mostly null
                                                      'sr_id', #ids mostly null
                                                      'main_sr_id', #mostly 0
                                                      'node_id', #mostly null
                                                      'random_ques', #_,0,1 mostly null
                                                      'random_options', #_,0,1 mostly null
                                                      'is_streaming', #0,1
                                                      'deleted_at', #
                                                      'created_at',
                                                      'updated_at', #
                                                     ]].copy()

# ai_video_kit  #Same id id many times in ai_video_kit catcher_id and id start from 13

In [ ]:
ai_video_kit_df.shape

In [ ]:
ai_video_kit_df.head(5)

In [ ]:
ai_video_kit_df['deleted_at'].value_counts()

In [ ]:
ai_video_kit_selected_df = ai_video_kit_df[['id', #starts from 13
                                            'catcher_id',
                                            'title',#react, kit, python, javascript
                                            'slug',#jquery, react
                                            'answer_duration',#time takent o answer@@
                                            'question_set',
                                            'min_experience',#Experience of candidateeeeeeeeeeeeeeeee or..??@@
                                            'max_experience',#............................................??@@
                                            'interview_level',#2,3,1 .............................................??@@
                                            'evaluation_keywords',#["Coding Skills"],["Python", "Jquery", "Laravel"]
                                            'is_active',#,
                                            'deleted_at',#Null
                                            'created_at',
                                            'updated_at'
                                           ]].copy()

# jobma_pitcher_applied_jobs_df

In [ ]:
jobma_pitcher_applied_jobs_df

In [ ]:
jobma_pitcher_applied_jobs_selected_df = jobma_pitcher_applied_jobs_df[['jobma_applied_id', #starts from 13
                                                                        'jobma_pitcher_id',#59540,59631,59775 likee
                                                                        'jobma_post_id',#0,763,759,770,771
                                                                        'catcher_id',#
                                                                        'jobma_applied_date',#
                                                                        'jobma_contacted_date',#
                                                                        'jobma_contacted_text',#
                                                                        'status',#0,1,2,3,4---------->
                                                                        'tags',#test,arp,good,php,java
                                                                        'jobma_assessment_id',#float values  118.0,147.0,148.8.... mostly 0
                                                                        'invitation_id',#ids, mostly 0
                                                                        'documents',#mostly null or stringresums, summary
                                                                        #'status_name',#Null
                                                                        'pre_recorded_payment_status',#0,1 mostly 0
                                                                        'live_interview_payment_status',#0,1 mostly 0
                                                                        'apply_mode',#0,1,2,3,4,5,6 mostly
                                                                        'jobma_interview_rounds',#0,1,2,3,4
                                                                        'avg_ai_score',#Score generated by the AI found in only 15 tables
                                                                        'pre_screen_qualify',#0,1,2
                                                                        'integration_source',#one value in one colum
                                                                        'source',#jobma,microsoft teams,ZOom mostly jobma
                                                                        'export',#0,1 almost all are 0
                                                                        'deleted_rounds',####Problem  may be ticket raise
                                                                        'deleted_at',#
                                                                        'created_at',#
                                                                        'updated_at'
                                                                       ]].copy()

In [ ]:
jobma_pitcher_applied_jobs_df.shape

In [ ]:
jobma_pitcher_applied_jobs_df['live_interview_payment_status'].value_counts()

In [ ]:
# for col in jobma_pitcher_applied_jobs_df.columns:
#     print(f"Value count fr--- {col}: {jobma_pitcher_applied_jobs_df[col].nunique()}")
#     print(f"Value counts for column: {jobma_pitcher_applied_jobs_df[col].value_counts().head(10)}\n\n")

In [ ]:
jobma_pitcher_applied_jobs_df

#Candidate details may be
# jobma_pitcher

In [ ]:
jobma_pitcher_df

In [ ]:
jobma_pitcher_selected_df=jobma_pitcher_df[['jobma_pitcher_id', 
                                            'jobma_taleo_id',   #all are  0
                                            # 'jobma_pitcher_fname',
                                            # 'jobma_pitcher_lname', 
                                            # 'jobma_pitcher_email', 
                                            # 'email_verified',#none,1,0-->none
                                            # 'jobma_pitcher_alt_email', #mostly null
                                            # 'jobma_pitcher_bdate', #Candidate age can be find from here #more than half null
                                            # 'jobma_pitcher_sex', #null
                                            # 'phone_code', 
                                            # 'jobma_pitcher_phone', 
                                            'phone_verified', #
                                            # 'otp',
                                            # 'otp_expired_at',
                                            # 'jobma_secondary_phone', 
                                            # 'jobma_pitcher_address',
                                            # 'jobma_pitcher_city', 
                                            # 'jobma_pitcher_state', #numerical categorial value
                                            # 'jobma_pitcher_zip',
                                            # 'jobma_pitcher_fax', 
                                            # 'jobma_pitcher_country', ##numerical categorial value
                                            # 'jobma_pitcher_photo',#
                                            'jobma_pitcher_profile_status', #None, 0, 1 Almost none
                                            'deleted_at',#null
                                            'jobma_pitcher_profile_is_delete', #null,0
                                            'jobma_pitcher_type',#0, Null-------------------------->??

                                            # 'jobma_pitcher_qrcode', #
                                            # 'jobma_pitcher_url', #
                                            'url_type', #0,1  all 0
                                            'url_password',#null, _, 
                                            # 'jobma_pitcher_url_customized',#0,1 all 0
                                            'jobma_referer',######None, _, jobma, monster, Who ia taking the candidate or something..............???
                                            'source',#Direct
                                            'ats',#0, 130, 129, 126..... most 0
                                            'is_first_login',#0,1---0 
                                            'latitude', #0.0000 mostly
                                            'longitude',  #0.0000 mostly
                                            'ulat',#None 34420,0 all34420
                                            'api_key',

                                            'created_at', 
                                            'updated_at', 
                                            'latlon_updated',#nan, 1.0---NaN

                                            'jobma_pitcher_specialization', #none,    4,3,1
                                            'jobma_pitcher_emp_auth',#None --34432,      1 2 3

                                            'is_email_send', #Nan
                                            'step', #####################0,4,1,2 Hiring step may be
                                            'isWalkthroughCompleted',#0,1 alll 0

                                            'notified_milestones', #null
                                            'pitcher_apple_id', #none
                                           ]]

In [ ]:
jobma_pitcher_df['jobma_pitcher_id'].nunique()

In [ ]:
import pandas as pd

def compute_value_counts(df):
    for column in df.columns:
        print(f"Value counts for {column}:---{df[column].nunique()}")
        print(df[column].value_counts(dropna=False).head(10))
        print("--" * 20, "\n")

compute_value_counts(jobma_employer_job_posting_df)

# jobma_employer_job_posting #Mostly it holds the candidates details

In [ ]:
jobma_employer_job_posting_df.shape

In [ ]:
jobma_employer_job_posting_df.isna().sum().sort_values(ascending=False).head(35)

In [ ]:
jobma_employer_job_posting_selected_df=jobma_employer_job_posting_df[['jobma_job_post_id',
                                                                            'taleo_job_id', #196 unique id
                                                                            'jobma_catcher_id', ############1292 unique values in it
                                                                            'job_assessment_kit_id',#
                                                                            'ai_live_kit_id', #Mostly null 0.0,17.0,1698.0.... @6
                                                                            'jobma_job_title', #Job titles as new job, job by position,timed,new,
                                                                            'slug',#######sameas title but more
                                                                            # 'jobma_job_description', #May be job descriptions
                                                                            # 'jobma_job_notes', #notes adding for candidate @27
                                                                            'jobma_job_type',#@14, contract,permanent,part time, intern
       
                                                                            'job_dur_year', #@12, 0.0,1.0...16
                                                                            'job_dur_month', 
                                                                            'jobma_job_min_exp',########minimum experience may be used for prescreening or min exp
                                                                            'jobma_job_max_exp', ######max experience null,0.0.....
                                                                            'jobma_job_min_salary', #####salary offeredn or candidate salary

       
                                                                            'ai_rating_params',
                                                                            'jobma_job_sal_negotiable', #nan, 0.0,1 @2
                                                                            'jobma_job_sal_comments',#rate of sala pay mostly none
                                                                            'jobma_job_qualification', #952 value can be minimized
                                                                            'jobma_job_locations', #job location may be offered
                                                                            'jobma_job_industry',#it, medical, telecommunication..... categorial data
       
                                                                            'jobma_job_functional_areas', #it, eng, biotech etc
                                                                            'jobma_job_keywords',#keywords, pega, analyst, java, development
       
                                                                            'jobma_job_currency',#@12, usd, inr, 1,2,3,4 mostly null
                                                                            'jobma_job_salary_type',#annual, monthly, hourly, weekly
       
                                                                            'jobma_job_recruiter_name', #who recruited.......................>>mostly ssi, ssi
                                                                            #'jobma_job_recruiter_email',
       
                                                                            #'jobma_job_recruiter_phone', 
                                                                            'jobma_job_recruiter_ext',#some categorial code 7895,2656 like
       
                                                                            # 'jobma_job_recruiter_website', 
                                                                            # 'jobma_job_company_name',
       
                                                                            # 'jobma_job_company_profile', #intro of cmpy
                                                                            # 'jobma_job_company_website',
       
                                                                            # 'jobma_job_company_url_redirect', 
                                                                            'jobma_job_notice_period',#may be used when while reccomendind candidates in future, 0,3,2,4,1,5-->0
       
                                                                            # 'jobma_job_expiry_date', 
                                                                            'jobma_job_apply_count',#required but nullllll...........>>???
       
                                                                            'jobma_job_view_count', #required but nullllll...........>>???
                                                                            'jobma_job_inactive_date',#date for job inactivity
       
                                                                            'jobma_job_inactive_reason', #reason for inactivity mostly none, test, ok...
                                                                            # 'jobma_job_company_show',#0
       
                                                                            # 'jobma_job_recruiter_show', #0
                                                                            # 'jobma_job_interview_questions_ids',
       
                                                                            # 'jobma_question_think_time', 
                                                                            'jobma_question_takes',#can be used in recommender
       
                                                                            'jobma_job_interview_questions_durations', #can be used in recommender 
                                                                            # 'jobma_job_video_link',#none, yt_link ....
       
                                                                            'jobma_job_video_status', #1, None, null
                                                                            'video_flag', #Can be used in recommender, 0,1,2--->
                                                                            'jobma_job_status',#0,1-->0
       
                                                                            # 'jobma_job_filename', #none
                                                                            'approval', #1,0,2
                                                                            'jobma_job_paper_ids',#mostly none@31
       
                                                                            # 'optional_ques', #0
                                                                            # 'optional_ques_text', #none
                                                                            # 'job_subscription_status',#1
       
                                                                            'won_source_job_id', #None, 43-9061,51-1011... 
                                                                            'won_profile_name', #None, officeclerk,general..................>>>>??
                                                                            'won_job_status',  #none, 1 mostly none
       
                                                                            'applicant_count', #nan,0.0,32
                                                                            'is_deleted', #nan, 0.0
                                                                            'is_hot', #0.0, nan, 1.0
                                                                            'source', #0,1 @2
                                                                            # 'source_id',  #@40, idss
       
                                                                            'is_private_job', #0,1, @3
                                                                            'google_schema',   #, _, 1,   #@2
                                                                            'monster_post_id', #None, @17
                                                                            'bamboo_job_id',#0
                                                                      
                                                                            'created_at', 
                                                                            'updated_at', 
                                                                            'jobma_job_created_date']] #Job creation  date by client

In [ ]:
compute_value_counts(jobma_employer_job_posting_df)

# jobma_pitcher_invitations

In [ ]:
jobma_pitcher_invitations_df.shape

In [ ]:
jobma_pitcher_invitations_df.columns

In [ ]:
# compute_value_counts(jobma_pitcher_invitations_df)

In [ ]:
jobma_pitcher_invitations_df.info()

In [ ]:
# jobma_pitcher_invitations_selected_df

In [ ]:
jobma_pitcher_invitations_selected_df=jobma_pitcher_invitations_df[['id', 
                                                                  'jobma_post_id', 
                                                                  'jobma_catcher_id', #@1018
                                                                  'jobma_pitcher_id', #@33197
                                                                  'applied_id', #@18519
                                                                  
                                                                  'is_invited', #1,2,-
                                                                  # 'jobma_pitcher_email',
                                                                  # 'jobma_invitation_date', 
                                                                  # 'jobma_invitation_expire_date',
       
                                                                  'interview_start_time', #Usage time-------------######------------------Interaction with candidate
                                                                  'interview_end_time', #Usage time---------------######----------------Interaction with candidate
                                                                  # 'invitation_timezone',#asia,colombo
       
                                                                  # 'jobma_invitation_message', 
                                                                  'jobma_interview_round', #nan, 1.0 2.0.....8#################
                                                                  'stages',############0,1,2,3
       
                                                                  'jobma_interview_mode', #1,2,3,4,0
                                                                  # 'jobma_interview_room', #0
                                                                  # 'jobma_interview_token',#tokens mostly none
       
                                                                  'pre_recorded_token', #-, None
                                                                  'jobma_interview_status', ############3,2,4,0,1,6,5,- @8
                                                                  'assessment_kit_id',#idd
       
                                                                  'assessment_question_set', #question set used as intro, jr python developer @9806 object value
                                                                  'pre_screening', #@83 Questionss
                                                                  'pre_screen_qualify',#1,0,2
       
                                                                  'application_settings', ###############@2415 Settings turned on by client is important feature#########
                                                                  # 'practice_question', 
                                                                  'interview_type',#@5,          ###1,2,3,4,----------->>
       
                                                                  'answer_duration', #####################answer duration for interaction of client how much time client spends and about candidate knowledge
                                                                  'interview_time_lapse',######@0325   0,60,10,,20,120,
       
                                                                  # 'interview_complete_notified_email', #eamil to confirm
                                                                  # 'jobseeker_signup_confirmation', #0,1-->0
       
                                                                  'signup_form_options', #lot of value
                                                                  'can_request_retake', #@2   0,1
                                                                  'active', #0,1
       
                                                                  'prerecorded_email_notification', #email notifications
                                                                  'br_id', ###@34, 0.0, 58.0, 74.0
                                                                  'integration_source', #1
       
                                                                  'callback_url', #url giving to callback
                                                                  'acceptation', ######################3,1,2 mostly 3
                                                                  'reject_reason',#####################None, 1, 2
       
                                                                  'auto_send_reminder_max', #####@6        0,1,3,2,9,22
                                                                  'interview_platform_status', #####@2   0,1
                                                                  'source',#########@4,    None,0,2,1
       
                                                                  'live_interview_source', #None, 0, 1---->None
                                                                  'live_interview_data',###################@88   dictionary
                                                                  
                                                                  'deleted_at',
                                                                  'created_at', 
                                                                  'updated_at']]

# jobma_interviews_df.shape

In [ ]:
#candidate interview response data (Pre-recorded type) can be used for the evalaution of candidate

In [ ]:
jobma_interviews_df.shape

In [ ]:
jobma_interviews_df.columns

In [ ]:
jobma_interviews_selected_df=jobma_interviews_df[['id',#@21999
                                                  'jobma_post_id',#@3916
                                                  'jobma_pitcher_id',#@15360
                                                  'jobma_catcher_id',#@865
                                                  'interview_applied_id', #@19057
                                                  'jobma_invitation_id', #@19044
                                                  'jobma_interview_question_id',#1 

                                                  
                                                  'jobma_answers',# @19621 dict of question ans
                                                  'jobma_video_answer',#@1 none,-

                                                  'retake_requested', #@2 0,1-->0
                                                  'payment_status', #@2 1,0--->1
                                                  'interview_rate',######################@81 0.0,1.0,2.0,3.0,4.0,....10.0............>>

                                                  'interview_credit',#@58  0.0,1.0,....10.0 ----->1.0
                                                  'view_date', ###################################
                                                  'subscription_type',#@3 0,1,_, ---->0

                                                  'interview_cost_type', #@2 0,1
                                                  'evaluated_by', #@684 who evaluated the candidate may be ,,,, 0.0,Nan, 7151, 2335,...
                                                  'is_streaming', #@4   1,3,0,2---->1
                                                  
                                                  'deleted_at',
                                                  'created_at', 
                                                  'updated_at']]

In [ ]:
#function to check the no of unique values and top values in table
# compute_value_counts(jobma_interviews_df)

# jobma_ai_interviews_df now
#candidate interview response data (just for AI Live Interview type)

In [ ]:
jobma_ai_interviews_df.shape

In [ ]:
jobma_ai_interviews_df.info()

In [ ]:
jobma_ai_interviews_df.columns

In [ ]:
jobma_ai_interviews_selected_df=jobma_ai_interviews_df[['id',
                                                        'jobma_post_id',#@8 
                                                        'jobma_pitcher_id', #@66 #33421--49, 34089--13, 
                                                        'jobma_catcher_id',#@3,  64827-3, 64811-2....
       
                                                        'interview_applied_id',#@68, 64827--3, 648112 
                                                        'jobma_invitation_id',#@73 575621-2, 574473--1
                                                        'jobma_answers', #@72 Video answers, evaluations dictionary
       
                                                        'payment_status', #@2 1,0
                                                        'interview_rate',#@3,  1.0, 0.0, 2.0...............>>??
                                                        'interview_credit',#@2   1.0, Nan, 2.0
                                                        'view_date',#date when does it view or evaluated
       
                                                        'subscription_type',#@1  0 in all
                                                        'interview_cost_type',#@1  0 in all
                                                        'cron_status',#@3   1,2,0-->1,2
                                                        'deleted_at',
       
                                                        'created_at',
                                                        'updated_at']]

In [ ]:
# compute_value_counts(jobma_ai_interviews_df)

# Now Report table
#different types of saved reports.

In [ ]:
report_df

In [ ]:
report_df.columns

In [ ]:
report_selected_df=report_df[['id',
                              'employer_id',#4 , 1873--79, 8464--9, 9315--8, 6543--2
                              'name',#@58, names
                              'category',#@4--, 1,3,,2,4--->1mostly
                              'created_on',
                              'file',#file name
                              'auto_report_status',#@2 0,1---->0
                              'auto_report_type',#@3,    0,2,1...>0
                              'auto_report_type_value', #@ None and dates
       
                              'filter_status_json',#@13, dict and status , invite, saubac,...
                              'required_filter_column',#@3, None,[1], [1,2], [1,2,3]---->None
                              
                              'created_at',
                              'updated_at',
                              'deleted_at']]

In [ ]:
# compute_value_counts(report_df)

# shared_report
#It will tell who share( parent or sub)----Share with sub-account or with main account

In [ ]:
shared_report_df.shape

In [ ]:
shared_report_df.columns

In [ ]:
shared_report_selected_df=shared_report_df[['id',#@589, 
                                            'report_id',#@29,  Nan, 89.0,113.0,55.0,.....
                                            'report_type',#@5,  category, report type, invite_listing, interview count, jobposting, integration
                                            'shared_by',#@83    1873--151, 2334--68, 3678--50, 1372--26
                                            'shared_to',#@174   9369---33, 3679--28..
                                            'is_new',#@3,  1, 0 , -
                                            'file_name',#
                                            'deleted_by',#@3, null mostly
                                            'message',#190 test, test, ok, may be some kind of message
                                            
                                            'created_at',
                                            'updated_at']]

In [ ]:
shared_report_df

In [ ]:
compute_value_counts(shared_report_df)