In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [3]:
jobma_catcher_df = pd.read_sql("SELECT * FROM jobma_catcher", engine)

In [4]:
jobma_catcher_df.to_csv('jobma_catcher_df.csv', index=False)

,jobma_catcher_id,jobma_catcher_fname,jobma_catcher_lname,jobma_catcher_dob,jobma_catcher_video_status,jobma_catcher_company,org_type,sec_ques_id,security_ans,jobma_about_company,...,referral_credit,company_size,theme,flag,jobma_auto_recording_status,jobma_scenario_question_status,ai_live_interview,ms_teams_chat_reference,bot_audio,approval
0,1,jayant,,None,None,Jobma,1,0,,,...,0,1-25,0,0,0,0,0,None,1,0
1,92,,,2016-11-22,1,Select Source International,,1,,Select Source International is a Global Soluti...,...,0,None,0,0,0,0,0,None,1,0
2,96,Gaurav,Arora,2016-11-01,1,Select Source International,employer,0,,Select Source International is a Global Soluti...,...,0,None,0,0,0,0,0,None,1,0
3,106,,,2016-09-26,1,Singhal System Solutions Pvt. Ltd.,employer,0,,IT Company,...,0,None,0,0,0,0,0,None,1,0
4,117,Krishna,Kant,2016-09-26,1,Select Source International,employer,0,,Select Source International is a Global Soluti...,...,0,None,0,0,0,0,0,None,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7667,9437,new own data account check,,None,None,JOBMA,1,0,,Description from settings new company descript...,...,0,1-25,0,0,0,0,0,None,1,0
7668,9439,new account to check evaluate,,None,None,JOBMA,1,0,,Description from settings new company descript...,...,0,1-25,0,0,0,0,0,None,1,0
7669,9441,new account to check changed session,,None,None,JOBMA,1,0,,Description from settings new company descript...,...,0,1-25,0,0,0,0,0,None,1,0
7670,9443,nayan,,None,None,Jobma,,0,,What is Lorem Ipsum?\r\nLorem Ipsum is simply ...,...,0,500-1000,0,0,0,0,0,None,1,0
7671,9445,Serge brian,,None,None,Jobma,1,0,,,...,0,1-25,0,0,0,0,0,None,1,0

In [5]:
jobma_catcher_df.to_csv('jobma_catcher_df.csv', index=False)

In [6]:
jobma_login_df = pd.read_sql("SELECT * FROM jobma_login", engine)

In [8]:
jobma_login_df.to_csv('jobma_login_df.csv', index=False)

In [9]:
jobma_wallet_df = pd.read_sql("SELECT * FROM wallet", engine)

In [10]:
jobma_wallet_df.to_csv('jobma_wallet_df.csv', index=False)

In [11]:
jobma_subscription_df = pd.read_sql("SELECT * FROM subscription_history", engine)

In [12]:
jobma_subscription_df.to_csv('jobma_subscription_df.csv', index=False)
print("Done")

Done

In [13]:
jobma_catcher_language_df = pd.read_sql("SELECT * FROM jobma_catcher_language", engine)

In [14]:
jobma_catcher_language_df.to_csv('jobma_catcher_language_df.csv', index=False)
print("Done")

Done